# Generated by Django 5.1.6 on 2025-02-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='id',
            new_name='usr_id',
        ),
    ]
